### ISSUE TITLE
DB-util incompatible with flexipool-spring boot starter

### ISSUE THREAD

**Issue by JosRoseboom** [vladmihalcea/db-util#18]
The flexipool spring boot starter 1.6.2 (https://mvnrepository.com/artifact/com.github.gavlyukovskiy/flexy-pool-spring-boot-starter) does not work with datasource-proxy 1.4.7 , which is the dependency version in the pom of db-util. It will throw a NoClassDefFounderError:

`java.lang.NoClassDefFoundError: net/ttddyy/dsproxy/proxy/GlobalConnectionIdManager
	at com.github.gavlyukovskiy.boot.jdbc.decorator.dsproxy.DataSourceProxyConfiguration.connectionIdManagerProvider(DataSourceProxyConfiguration.java:49) ~[datasource-decorator-spring-boot-autoconfigure-1.6.2.jar:na]`

This is because GlobalConnectionIdManager is added in version 1.6.0 of datasource-proxy => https://ttddyy.github.io/datasource-proxy/docs/current/api/net/ttddyy/dsproxy/proxy/GlobalConnectionIdManager.html

When I explicitly added a dependency to version 1.7 of datasource-proxy the problem was gone. 

Maybe there are other considerations that make upgrading the dependency not trivial.

**Comment by vladmihalcea** [comment]
Thanks for the hint. I'll check it out and see if I can do an upgrade.

**Comment by vladmihalcea** [comment]
Fixed by [this commit](https://github.com/vladmihalcea/db-util/commit/3c278cd6feab77f80fa3d35cbc21dda1156be45e).

**Comment by vladmihalcea** [comment]
I released the `1.0.5` version that uses the `1.6` version of `datasource-proxy`.
